/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

import app.src.main.java.org.example.SunMailService;
import app.src.main.java.org.example.IMailService;
import app.src.main.java.org.example.SimpleJavaMailService;

public class App {

    static Properties p = new Properties();

    private static String USER_NAME; // GMail user name (just the part before "@gmail.com")
    private static String PASSWORD ;

    public static List<String> readEmailsFromCSV(String fileName) throws FileNotFoundException {
        try (InputStream inputStream = App.class.getClassLoader().getResourceAsStream(fileName)) {
            if (inputStream == null) {
                System.out.println("File not found: " + fileName);
                return new ArrayList<String>();  // Return empty list if file is not found
            }
            BufferedReader br = new BufferedReader(new InputStreamReader(inputStream));
            return br.lines().map(line -> line.split(",")[1])
                    .collect(Collectors.toList());
        } catch (Exception e) {
            e.printStackTrace();
            throw new FileNotFoundException();
        }
    }

    public static void main(String[] args) throws FileNotFoundException {



        try(FileReader reader = new FileReader("local.properties");){
            p.load(reader);
        } catch (Exception e) {
            System.out.println("Error loading properties file.");
            e.printStackTrace();
            return; // Exit if loading properties fails
        }

        // Retrieve properties after loading them
        USER_NAME = p.getProperty("gmailUser");
        PASSWORD = p.getProperty("gmailPassword");
        List<String> receipients = readEmailsFromCSV("emails.csv");

        String from = USER_NAME;
        String pass = PASSWORD;
        String[] to = receipients.toArray(new String[0]) ; // list of recipient email addresses
        String subject = "Java simple mail example csv";
        String body = "Welcome to Java mail!";

        System.out.println(from+' '+ Arrays.toString(to) +' '+ pass);

        // SunMailService.sendFromGMail(from, pass, to, subject, body);
        IMailService mailService = new SunMailService();
        mailService.sendFromGMail(from, pass, to, subject, body);
    }

}
